sudo: required
dist: trusty
language: python
jobs:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
notifications:
  email: false
install:
    - pip install -U pip
    - pip install tox-travis coverage==4.3.4
script: tox
deploy:
  on:
    repo: aschampion/diluvian
    python: 3.5
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ahez/10Y7uxpSuJyKO6QPelGeGkKpysvT7Ahe5WkhX+tcZA2HaA2RPXRaZj2A/aIz9ncDq/S7G8WOwdWCwrUjmXgS+H1Wrt8M+b2Rpui58q4IR+mCOa26+zPQwckMLhp/ZHwGj8amK7bZXg3YBMLSqk1WHSkp0lK45zgP02+m1VddaeG9NhhexScFXH96P3Mmvi4TypPOgsyQ6Rf1Z/VAJbujPV8Z8UiqVmu5ovgsGqVK6VlZ4gcuoQVT7nbiKcH73jczaClt0gd6ZFQj6afsraVLQEUVNPdUZtT6MaTcTWNejujppD3GDlLI4xO+m+bb0tTlMqmGaSLicMeibmq7w9CnoGaFF4ZJSFMeMzOyA6lGMVMBLumKfbgivzTYeG8ctKGgeBOR/4KYyDeLVD6z4inoJ40NfdHeGVUWqHRUcd21le/i4ChZNMbEwRNj82Sdq4vPZtNjP+jh68+hjQ1msEkiStVWQz66Cigv/fTVAZwCtW+H3A+YBfwSbgFTROk76jh9ywVDlLQCsu7eaHbgIJBW4lm2pxNp+is0Vb6oA+wbDKwbmJAzIAlUmpaE/pnIBScuN4AUXwOBvOCublH6M++TX12MjXAUghw2VDj3O4GuaNYUGMYmR0luoph9jp0X5HS10sST+KeDwWcjXwKH8ghATqQiUcWizFmkOpuppI=
  provider: pypi
  user: aschampion
